# pretty good commented example
# https://gist.github.com/jhass/a5ae80d87f18e53e7b56

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

